version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: workshop-db
      POSTGRES_PASSWORD: changemeinprod