name: Workshop Manager API CI

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # Windows related permission fix
      - name: Set executable permission for mvnw
        run: chmod +x backend/mvnw

      - name: Build with Maven
        run: |
          cd backend
          ./mvnw clean compile

  test:
    runs-on: ubuntu-latest
    name: Run backend tests
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # Windows related permission fix
      - name: Set executable permission for mvnw
        run: chmod +x backend/mvnw

      - name: Run unit tests
        run: |
          cd backend
          ./mvnw clean test